name: Publish Gem

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_publish:
    name: Build, tag & publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1

    - name: Get version
      id: version
      run: |
        VERSION=$(ruby -e "require './lib/tip_tap/version'; puts TipTap::VERSION")
        echo "::set-output name=version::$VERSION"

    - name: Create and push tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag v${{ steps.version.outputs.version }}
        git push origin v${{ steps.version.outputs.version }}

    - name: Run tests
      run: |
        bundle install
        bundle exec rspec

    - name: Build and publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: Release ${{ steps.version.outputs.version }}
        body: |
          See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md) for details.
        draft: false
        prerelease: false
